baseURL = "https://vflins.github.io/"
favicon = "/favicon"
languageCode = "pt_BR"
defaultContentLanguage = "pt-br"
title = "Vitor Lins"
theme = ["ananke"]
sectionPagesMenu = "main"
enableEmoji = true

[params]
site_logo = "images/icons/logo-vitor-symbolic.svg"
date_format = ":date_full"
locale = "pt_BR"
read_more_copy = "continue lendo"
custom_css = ["colors.css", "layout.css", "style.css"]
background_color_class = "bg-gradient-teal-white"
mainSections = ["blog"]

[taxonomies]
tag = "tags"
category = "categories"

[params.ananke.social.share]
icons = true
networks = ["email", "facebook", "instagram", "linkedin", "whatsapp"]

[params.ananke.social.linkedin]
username = "vflins"

[params.ananke.social.instagram]
username = "vitorlins.consultor"

[params.ananke.social.github]
username = "VFLins"

[params.ananke.social.follow]
new_window_icon = true
networks = ["instagram", "github"]

[markup.highlight]
style = "trac"

[markup.goldmark.parser.attribute]
block = true
